name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # Build & Push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smartgenie:v1.0

      # Deploy on EC2
      # Deploy on EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}   
          script: |
            # Create .env directly on EC2
            echo "${{ secrets.PROD_ENV_FILE }}" > /home/ubuntu/.env
      
            # Pull latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/smartgenie:v1.0
      
            # Stop & remove old container
            docker stop smartgenie || true
            docker rm smartgenie || true
      
            # Clean up unused Docker resources
            docker system prune -af --volumes
      
            # Run new container
            docker run -d --name smartgenie \
              --env-file /home/ubuntu/.env \
              -p 80:3000 \
              ${{ secrets.DOCKER_USERNAME }}/smartgenie:v1.0

