name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # GitHub-hosted runner (build happens here)

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sasaurabh11/smartgenie:latest

      # Deploy on EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}   # Your private key
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sasaurabh11/smartgenie:latest
            docker stop smartgenie || true
            docker rm smartgenie || true
            docker run -d --name smartgenie \
              --env-file /home/ubuntu/.env \
              -p 80:3000 \
              ${{ secrets.DOCKER_USERNAME }}/sasaurabh11/smartgenie:latest
